---
language: python
python: "3.8"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  - pip install -r https://raw.githubusercontent.com/nephelaiio/ansible-role-requirements/master/requirements.txt
  - ansible --version

script:
  - travis_wait make test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
